using System;
using EmptyProject.Core.BaseLogicComponents;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using MonoGame.Kernel2D.Animation;
using K2D = MonoGame.Kernel2D.Animation;
using XnaVector = Microsoft.Xna.Framework.Vector2;

namespace EmptyProject.Core
{
    /// <summary>
    /// The main class for the game, responsible for managing game components, settings, 
    /// and platform-specific configurations.
    /// </summary>
    public class EmptyProjectGame : Game
    {
        #region autogenerated code
        // Resources for drawing.
        private GraphicsDeviceManager graphicsDeviceManager;

        /// <summary>
        /// Indicates if the game is running on a mobile platform.
        /// </summary>
        public readonly static bool IsMobile = OperatingSystem.IsAndroid() || OperatingSystem.IsIOS();

        /// <summary>
        /// Indicates if the game is running on a desktop platform.
        /// </summary>
        public readonly static bool IsDesktop = OperatingSystem.IsMacOS() || OperatingSystem.IsLinux() || OperatingSystem.IsWindows();

        /// <summary>
        /// Initializes a new instance of the game. Configures platform-specific settings, 
        /// initializes services like settings and leaderboard managers, and sets up the 
        /// screen manager for screen transitions.
        /// </summary>
        public EmptyProjectGame()
        {
            graphicsDeviceManager = new GraphicsDeviceManager(this);

            // Share GraphicsDeviceManager as a service.
            Services.AddService(typeof(GraphicsDeviceManager), graphicsDeviceManager);

            Content.RootDirectory = "Content";

            // Configure screen orientations.
            graphicsDeviceManager.SupportedOrientations = DisplayOrientation.LandscapeLeft | DisplayOrientation.LandscapeRight;
        }

        /// <summary>
        /// Initializes the game, including setting up localization and adding the 
        /// initial screens to the ScreenManager.
        /// </summary>
        protected override void Initialize()
        {
            base.Initialize();
        }
        #endregion

        /// <summary>
        /// Updates the game's logic, called once per frame.
        /// </summary>
        /// <param name="gameTime">
        /// Provides a snapshot of timing values used for game updates.
        /// </param>
        protected override void Update(GameTime gameTime)
        {
            if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed
                || Keyboard.GetState().IsKeyDown(Keys.Escape))
                Exit();
            _input.Update();
            PollInput();

            ap.Update(gameTime);

            if (_currentState == PlayerState.Dashing && ap.HasFinishedPlaying)
            { 
                ap.Play(sheet.Animations["idle"]);
                _currentState = PlayerState.Idle;
            }
            
            base.Update(gameTime);
        }

        private void PollInput()
        {
            if (_input.IsIdle())
            {
                _currentState = PlayerState.Idle;
                ap.Play(sheet.Animations["idle"]);
                return;
            }

            if (_input.MoveLeft()) _facingRight = false;
            else if (_input.MoveRight()) _facingRight = true;

            bool moving = _input.MoveLeft() || _input.MoveRight();
            if (moving)
            {
                float speed = _facingRight ? _physics.RunSpeed : -_physics.RunSpeed;
                _playerPosition = new(_playerPosition.X + speed, _playerPosition.Y);
            }

            if (_currentState != PlayerState.Dashing && _currentState != PlayerState.Jumping)
            {
                if (_currentState != PlayerState.Running)
                    _currentState = PlayerState.Running;

                if (ap.CurrentAnimationName != "run")
                    ap.Play(sheet.Animations["run"]);
            }

            // TODO: all this shit about dashing and jumping
            if (_input.DashPressed())
            {
                _currentState = PlayerState.Dashing;
            }

            if (_input.JumpPressed())
            {
                _currentState = PlayerState.Jumping;
            }
        }

        /// <summary>
        /// Draws the game's graphics, called once per frame.
        /// </summary>
        /// <param name="gameTime">
        /// Provides a snapshot of timing values used for rendering.
        /// </param>
        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.Gray);
            base.Draw(gameTime);

            sb.Begin();
            ap.Draw(sb, playerTexture, _playerPosition, _facingRight ? SpriteEffects.None : SpriteEffects.FlipHorizontally);
            sb.End();
        }

        protected override void LoadContent()
        {
            base.LoadContent();
            sb = new SpriteBatch(GraphicsDevice);
            ap = new K2D.AnimationPlayer();

            playerTexture = Content.Load<Texture2D>("Player/zero-fixed-rows");

            var rawspritemap = AnimationLoaderHelper.GetSpritesFromJson("spriteMap.json");
            sheet = AnimationLoaderHelper.TranslateIntoDomainModel(rawspritemap, playerTexture, "Zero");

            ap.Play(sheet.Animations["idle"]);
        }

        private SpriteBatch sb = null;
        private Texture2D playerTexture = null;
        private K2D.AnimationPlayer ap = null;
        private K2D.Spritesheet sheet = null;
        private PlayerState _currentState = PlayerState.Idle;
        private XnaVector _playerPosition = new(150, 400);
        private readonly PlatformerInputBridge _input = new();
        private bool _facingRight = true;
        private readonly PhysicsValues _physics = PhysicsValues.Default();


    }
}